version: '3'

services:
  # RabbitMQ service
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"     # Messaging port
      - "15672:15672"   # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  # Order Service
  order-service:
    image: dirtypatel/order-service:latest
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://myuser:mypassword@rabbitmq:5672/
      - PORT=3000
    depends_on:
      - rabbitmq

  # Product Service
  product-service:
    image: dirtypatel/product-service:latest
    ports:
      - "3030:3030"
    environment:
      - PORT=3030

  # Store Front
  store-front:
    image: dirtypatel/store-front:latest
    ports:
      - "80:80"
    environment:
      - VUE_APP_ORDER_SERVICE_URL=http://order-service:3000
      - VUE_APP_PRODUCT_SERVICE_URL=http://product-service:3030
    depends_on:
      - product-service
      - order-service
